import { createClient, type SupabaseClient } from '@supabase/supabase-js'
import type { Handler, HandlerEvent, HandlerResponse } from '@netlify/functions'
import type { Lead, LeadStatus } from '../../src/lib/types'
import { scoreLead } from '../../src/services/scoringService'

const WEBHOOK_HEADER = 'x-webhook-secret'

const FORM_CHATBOT = 'chatbot-lead'
const FORM_VALUATION = 'seller-valuation'
const FORM_NEWSLETTER = 'newsletter-signup'

type NetlifyWebhookPayload = {
  form_name?: string
  data?: Record<string, unknown>
  created_at?: string
  site_url?: string
}

/** Row shape for Supabase insert (id generated by DB). */
export type LeadInsertRow = {
  first_name: string | null
  last_name: string | null
  email: string | null
  phone: string | null
  address: string | null
  zip: string | null
  source: string
  original_lead_date: string | null
  pipeline_stage: string
  score: number
  status: LeadStatus
  has_home_to_sell: boolean | null
  budget_max: number | null
  listing_price: number | null
}

function jsonResponse(statusCode: number, body: Record<string, unknown>): HandlerResponse {
  return {
    statusCode,
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  }
}

function resolveSupabaseUrl(): string {
  const candidates = [
    process.env.SUPABASE_URL,
    process.env.VITE_SUPABASE_URL,
  ]
  const url = candidates.find((v) => v?.trim())?.trim()
  if (!url) {
    throw new Error('Missing SUPABASE_URL or VITE_SUPABASE_URL')
  }
  return url
}

function getServiceSupabase(): SupabaseClient {
  const url = resolveSupabaseUrl()
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY?.trim()
  if (!key) {
    throw new Error('Missing SUPABASE_SERVICE_ROLE_KEY')
  }
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  })
}

function verifyWebhookSecret(event: HandlerEvent): boolean {
  const expected = process.env.WEBHOOK_SECRET?.trim()
  if (!expected) return false
  const header =
    event.headers['x-webhook-secret'] ??
    event.headers['X-Webhook-Secret'] ??
    ''
  return header.trim() === expected
}

function parsePayload(event: HandlerEvent): NetlifyWebhookPayload {
  if (!event.body) {
    throw new Error('Empty request body')
  }
  const raw = event.isBase64Encoded
    ? Buffer.from(event.body, 'base64').toString('utf8')
    : event.body
  const parsed = JSON.parse(raw) as NetlifyWebhookPayload & {
    payload?: NetlifyWebhookPayload
  }
  if (!parsed || typeof parsed !== 'object') {
    throw new Error('Invalid JSON payload')
  }
  // Netlify outgoing webhooks often nest under `payload` (see Netlify docs).
  const envelope =
    parsed.payload && typeof parsed.payload === 'object'
      ? parsed.payload
      : parsed
  if (!envelope.form_name?.trim()) {
    throw new Error('Missing form_name')
  }
  return envelope
}

function stringField(data: Record<string, unknown>, key: string): string | null {
  const value = data[key]
  if (value === null || value === undefined) return null
  const s = String(value).trim()
  return s === '' ? null : s
}

function splitName(name: unknown): {
  first_name: string | null
  last_name: string | null
} {
  const full = typeof name === 'string' ? name.trim() : ''
  if (!full) return { first_name: null, last_name: null }
  const parts = full.split(/\s+/).filter(Boolean)
  if (parts.length === 1) {
    return { first_name: parts[0], last_name: null }
  }
  return {
    first_name: parts[0],
    last_name: parts.slice(1).join(' '),
  }
}

function parseIsoTimestamp(
  data: Record<string, unknown>,
  fallback?: string,
): string | null {
  const candidates = [
    stringField(data, 'timestamp'),
    fallback,
  ]
  for (const raw of candidates) {
    if (!raw) continue
    const d = new Date(raw)
    if (!Number.isNaN(d.getTime())) return d.toISOString()
  }
  return new Date().toISOString()
}

function parseBudgetMax(data: Record<string, unknown>): number | null {
  const value = data.budget
  if (typeof value === 'number' && Number.isFinite(value) && value > 0) {
    return Math.round(value)
  }
  const raw = stringField(data, 'budget')
  if (!raw) return null
  const digits = raw.replace(/[^0-9.]/g, '')
  if (!digits) return null
  const n = Number(digits)
  return Number.isFinite(n) && n > 0 ? Math.round(n) : null
}

function toLeadForScoring(row: LeadInsertRow): Lead {
  return {
    id: 'pending',
    first_name: row.first_name,
    last_name: row.last_name,
    email: row.email,
    phone: row.phone,
    address: row.address,
    zip: row.zip,
    source: row.source,
    original_lead_date: row.original_lead_date,
    last_contact_at: null,
    pipeline_stage: row.pipeline_stage,
    score: null,
    status: null,
    has_home_to_sell: row.has_home_to_sell,
    buying_or_renting: null,
    lender_status: null,
    budget_max: row.budget_max,
    listing_price: row.listing_price,
    created_at: null,
    updated_at: null,
  }
}

function applyScore(row: LeadInsertRow): LeadInsertRow {
  const { score, status } = scoreLead(toLeadForScoring(row))
  return { ...row, score, status }
}

/** Step 4: chatbot-lead field mapper (thesuepattigroup.ai FormData field names). */
export function chatbotMapper(
  data: Record<string, unknown>,
  createdAt?: string,
): LeadInsertRow {
  const { first_name, last_name } = splitName(data.name)
  const base: LeadInsertRow = {
    first_name,
    last_name,
    email: stringField(data, 'email'),
    phone: stringField(data, 'phone'),
    address: null,
    zip: null,
    source: 'website_chatbot',
    original_lead_date: parseIsoTimestamp(data, createdAt),
    pipeline_stage: 'new',
    score: 0,
    status: 'cold',
    has_home_to_sell: null,
    budget_max: parseBudgetMax(data),
    listing_price: null,
  }
  return applyScore(base)
}

/** Step 4: seller-valuation field mapper (HTML name attrs on home-valuation.html). */
export function valuationMapper(
  data: Record<string, unknown>,
  createdAt?: string,
): LeadInsertRow {
  const { first_name, last_name } = splitName(data.name)
  const base: LeadInsertRow = {
    first_name,
    last_name,
    email: stringField(data, 'email'),
    phone: stringField(data, 'phone'),
    address: stringField(data, 'property_address'),
    zip: stringField(data, 'zip'),
    source: 'website_valuation',
    original_lead_date: parseIsoTimestamp(data, createdAt),
    pipeline_stage: 'new',
    score: 0,
    status: 'cold',
    has_home_to_sell: true,
    budget_max: null,
    listing_price: null,
  }
  return applyScore(base)
}

/** Step 4: newsletter-signup field mapper. */
export function newsletterMapper(
  data: Record<string, unknown>,
  createdAt?: string,
): LeadInsertRow {
  const base: LeadInsertRow = {
    first_name: null,
    last_name: null,
    email: stringField(data, 'email'),
    phone: null,
    address: null,
    zip: null,
    source: 'website_newsletter',
    original_lead_date: parseIsoTimestamp(data, createdAt),
    pipeline_stage: 'new',
    score: 0,
    status: 'cold',
    has_home_to_sell: null,
    budget_max: null,
    listing_price: null,
  }
  return applyScore(base)
}

function routeMapper(
  formName: string,
  data: Record<string, unknown>,
  createdAt?: string,
): LeadInsertRow {
  switch (formName) {
    case FORM_CHATBOT:
      return chatbotMapper(data, createdAt)
    case FORM_VALUATION:
      return valuationMapper(data, createdAt)
    case FORM_NEWSLETTER:
      return newsletterMapper(data, createdAt)
    default:
      throw new Error(`Unknown form_name: ${formName}`)
  }
}

export const handler: Handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, body: '' }
  }

  if (event.httpMethod !== 'POST') {
    return jsonResponse(405, { error: 'Method not allowed' })
  }

  if (!verifyWebhookSecret(event)) {
    return jsonResponse(401, { error: 'Unauthorized' })
  }

  try {
    const payload = parsePayload(event)
    const formName = payload.form_name?.trim()
    if (!formName) {
      throw new Error('Missing form_name')
    }

    const data = payload.data ?? {}
    if (typeof data !== 'object') {
      throw new Error('Missing or invalid data object')
    }

    const row = routeMapper(formName, data, payload.created_at)
    const supabase = getServiceSupabase()

    const { data: inserted, error } = await supabase
      .from('leads')
      .insert(row)
      .select('id, source')
      .single()

    if (error) {
      console.error('[website-lead] insert failed:', error.message)
      throw new Error('Database insert failed')
    }

    console.log(
      `[website-lead] inserted id=${inserted.id} source=${inserted.source}`,
    )

    return jsonResponse(200, {
      ok: true,
      id: inserted.id,
      source: inserted.source,
    })
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error'
    console.error('[website-lead] error:', message)
    return jsonResponse(500, { error: 'Failed to process website lead' })
  }
}
